import { readFileSync, readdirSync, statSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, basename, relative, resolve } from 'node:path';

const DOCS_ROOT = resolve(import.meta.dirname, '..', '..', '..', 'docs');
const OUT_DIR = resolve(import.meta.dirname, '..', 'src', 'generated');
const OUT_FILE = join(OUT_DIR, 'docs-bundle.ts');

function stripFrontmatter(content: string): string {
  if (!content.startsWith('---')) return content;
  const endIndex = content.indexOf('---', 3);
  if (endIndex === -1) return content;
  return content.slice(endIndex + 3).trimStart();
}

function stripConceptLinks(content: string): string {
  return content.replace(/\[([^\]]+)\]\(\.\.\/concepts\/[^)]+\)/g, '$1');
}

function extractTitle(content: string): string {
  const match = content.match(/^#\s+(.+)$/m);
  return match ? match[1].trim() : '';
}

function walkDir(dir: string, files: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    if (entry === '.vitepress' || entry === 'node_modules') continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      walkDir(full, files);
    } else if (entry.endsWith('.md') && entry !== 'CLAUDE.md') {
      files.push(full);
    }
  }
  return files;
}

const files = walkDir(DOCS_ROOT).sort();

interface DocEntry {
  path: string;
  title: string;
  category: string;
}

const index: DocEntry[] = [];
const content: Record<string, string> = {};

for (const file of files) {
  const relPath = relative(DOCS_ROOT, file).replace(/\.md$/, '').replace(/\\/g, '/');
  const category = relPath.includes('/') ? relPath.split('/')[0] : 'root';

  let body = readFileSync(file, 'utf-8');
  body = stripFrontmatter(body);
  body = stripConceptLinks(body);

  const title = extractTitle(body) || basename(file, '.md');

  index.push({ path: relPath, title, category });
  content[relPath] = body;
}

if (!existsSync(OUT_DIR)) {
  mkdirSync(OUT_DIR, { recursive: true });
}

const output = `// Auto-generated by scripts/bundle-docs.ts — do not edit manually

export interface DocEntry {
  path: string;
  title: string;
  category: string;
}

export const DOCS_INDEX: DocEntry[] = ${JSON.stringify(index, null, 2)};

export const DOCS_CONTENT: Record<string, string> = {
${Object.entries(content)
  .map(([key, value]) => `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`)
  .join('\n')}
};
`;

writeFileSync(OUT_FILE, output, 'utf-8');
console.log(`Bundled ${files.length} docs → ${OUT_FILE}`);
