import { readFileSync, readdirSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, basename, resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..', '..', '..', 'docs', 'reference');
const OUT_DIR = resolve(import.meta.dirname, '..', 'src', 'generated');
const OUT_FILE = join(OUT_DIR, 'reference-docs.ts');

function stripFrontmatter(content: string): string {
  if (!content.startsWith('---')) return content;
  const endIndex = content.indexOf('---', 3);
  if (endIndex === -1) return content;
  return content.slice(endIndex + 3).trimStart();
}

function stripConceptLinks(content: string): string {
  return content.replace(/\[([^\]]+)\]\(\.\.\/concepts\/[^)]+\)/g, '$1');
}

function processFile(filePath: string): string {
  const raw = readFileSync(filePath, 'utf-8');
  let content = stripFrontmatter(raw);
  content = stripConceptLinks(content);
  return content;
}

const files = readdirSync(ROOT)
  .filter((f) => f.endsWith('.md'))
  .sort();

const entries: Record<string, string> = {};
for (const file of files) {
  const topic = basename(file, '.md');
  entries[topic] = processFile(join(ROOT, file));
}

if (!existsSync(OUT_DIR)) {
  mkdirSync(OUT_DIR, { recursive: true });
}

const lines = Object.entries(entries).map(
  ([key, value]) => `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`,
);

const output = `// Auto-generated by scripts/bundle-docs.ts — do not edit manually
export const REFERENCE_DOCS: Record<string, string> = {
${lines.join('\n')}
};
`;

writeFileSync(OUT_FILE, output, 'utf-8');
console.log(`Bundled ${files.length} reference docs → ${OUT_FILE}`);
